server:
  port: 8009
  servlet:
    context-path: /shiro
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userceshi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    serialization:
      write-dates-as-timestamps: true
  thymeleaf:
    prefix: classpath:templates/
  mvc:
    view:
      prefix: /templates
      suffix: .html

mybatis:
  mapper-locations: classpath*:mapper/**.xml


img.url.test: ceshi/

logging.level.com.lcs.mapper: DEBUG
ftp:
  username: root
  password: 123456
  ip: 139.129.91.3
  port: 8080